name: Build

on: [push]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.8]
        platform: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 PyInstaller
        python build_release.py --install-nsmblib
    - name: Build
      run: |
        python -OO build_release.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-${{ matrix.platform }}
        path: distrib
